# Generated by Django 5.0.7 on 2024-07-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offers',
            new_name='Discount',
        ),
    ]
