# Generated by Django 5.0.7 on 2024-07-22 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_offers_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='expire_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
